#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

OWNCLOUD_VERSION="9.1.8"
DESTDIR="/var/www/htdocs/owncloud"

MUNIN_PLUGINS="
	apache_accesses
	apache_processes
	apache_volume
	httpd_memory
	redis_connected_clients
	redis_per_sec
	redis_used_memory
"

echo "* Remove unused httpd config files"
HTTPD_CONF_RM="httpd-autoindex.conf
httpd-dav.conf
httpd-default.conf
httpd-info.conf
httpd-languages.conf
httpd-manual.conf
httpd-mpm.conf
httpd-multilang-errordoc.conf
httpd-ssl.conf
httpd-userdir.conf
httpd-vhosts.conf"

for CONF_RM in ${HTTPD_CONF_RM}; do
  rm -f /opt/local/etc/httpd/${CONF_RM}
done

echo "* Setup owncloud"
mkdir -p $DESTDIR/releases

cd $DESTDIR/releases
curl -L -O https://download.qutic.com/src/owncloud/owncloud-$OWNCLOUD_VERSION.tar.bz2
tar xf owncloud-$OWNCLOUD_VERSION.tar.bz2
rm owncloud-$OWNCLOUD_VERSION.tar.bz2
mv owncloud oc-$OWNCLOUD_VERSION
cd oc-$OWNCLOUD_VERSION
rm -rf config

cd apps
curl -L -O https://download.qutic.com/src/owncloud/apps-$OWNCLOUD_VERSION/calendar.tar.gz
curl -L -O https://download.qutic.com/src/owncloud/apps-$OWNCLOUD_VERSION/contacts.tar.gz
curl -L -O https://download.qutic.com/src/owncloud/apps-$OWNCLOUD_VERSION/bookmarks.tar.gz
curl -L -O https://download.qutic.com/src/owncloud/apps-$OWNCLOUD_VERSION/polls.tar.gz

tar xf calendar.tar.gz
tar xf bookmarks.tar.gz
tar xf contacts.tar.gz
tar xf polls.tar.gz

rm calendar.tar.gz
rm contacts.tar.gz
rm bookmarks.tar.gz
rm polls.tar.gz

cd $DESTDIR
ln -nfs $DESTDIR/releases/oc-$OWNCLOUD_VERSION current

chown -R www:www "$DESTDIR"

echo "* Change www for cronjobs"
usermod -d "$DESTDIR" -s /usr/bin/bash www

echo "* Activate munin plugins"
/opt/qutic/bin/munin-node-plugins ${MUNIN_PLUGINS}

echo "* Activate redis"
gsed -i \
     -e "s/# maxmemory <bytes>/maxmemory 256mb/" \
     -e "s/# maxmemory-policy noeviction/# maxmemory-policy allkeys-lfu/" \
     -e "s/# unixsocket \/tmp\/redis.sock/unixsocket \/var\/tmp\/redis.sock/" \
     /opt/local/etc/redis.conf

svcadm enable redis

# echo "* Enable ipfilter"
# svcadm enable svc:/network/ipfilter:default

# Clean up
echo "* Cleaning up."
rm /root/customize

# Prepare image for provisioning
sm-prepare-image -y
